baseURL = "https://rcy1314.github.io/noise/"
languageCode = "en-us"
title = "NOISE&分享"
theme = "onelou"

metaDataFormat = "yaml"
# pygmentsStyle = "trac"
# pygmentsUseClassic = true
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
disqusShortname = "appleboy48"
googleAnalytics = "UA-5766319-6"
enableRobotsTXT = true

rssLimit = 20  # 限制 RSS 文章输出的数量
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "NOISE"