baseURL = "https://rcy1314.github.io/arts/"
title = "NOISE"
keywords: NOISE
description: 记录分享
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme = "onelou"
params:
  opengraph:
    github: 'https://github.com/jyygithub'
    gitee: 'https://gitee.com/'
    csdn: 'https://blog.csdn.net/'
    juejin: 'https://juejin.cn/'
    jianshu: 'https://www.jianshu.com/'
    twitter: 'https://twitter.com'
    facebook: 'https://facebook.com'
  footer:
    hidePowered: false # Powered by Hugo & theme OneLou
    beian: # ICP备案号
    gongan:
      # code: 公安备案号XXXX
      # txt: 京公网安备XXXX号
    since: 2022
    copyright: XXX
  prefix:
    h2: "※ "
    h3: "✧ "

