baseURL = "https://rcy1314.github.io/noise/"
languageCode = "en-us"
title = "NOISE&分享"
theme = "onelou"

metaDataFormat = "yaml"
# pygmentsStyle = "trac"
# pygmentsUseClassic = true
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
disqusShortname = "appleboy48"
googleAnalytics = "UA-5766319-6"
enableRobotsTXT = true