baseURL: http://localhost:1313/
title: OneLou
keywords: OneLou
description: OneLou
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme: # "hugo-theme-onelou"
params:
  opengraph:
    github: 'https://github.com/rcy1314'
    twitter: 'https://twitter.com'
  footer:
    hidePowered: true # Powered by Hugo & theme OneLou
    beian: # ICP备案号
    gongan:
      # code: 公安备案号XXXX
      # txt: 京公网安备XXXX号
    since: 2023
    copyright: NOISE
  prefix:
    h2: "※ "
    h3: "✧ "
menu:
  navs:
    - name: Blog
      params:
        img: https://www.noisework.cn/assets/logo.png
      url: /post/
      weight: 1
    - name: 月度分享
      params:
        img: https://www.noisework.cn/assets/logo.png
      weight: 2
      url: /note/
    - name: 收藏阁
      params:
        img: https://www.noisework.cn/assets/logo.png
      url: /projects/
      weight: 2
    - name: About
      params:
        img: https://www.noisework.cn/assets/logo.png
      url: /about
      weight: 3
    - name: 404
      params:
        img: https://www.noisework.cn/assets/logo.png
      url: /404.html
      weight: 4
